export CONFLUENT_CLOUD_API_KEY="UOXCGDPWRUFA7FJE"
export CONFLUENT_CLOUD_API_SECRET="PBkxPqtx0iQj6s6B0FPhzn2AVn5+ToIQqaRTY9as/FSiv/zlShMAelpofYDFDb+w"

export AWS_ACCESS_KEY_ID="AKIA4CEZVBNW3ATOE4FT"
export AWS_SECRET_ACCESS_KEY="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"
export AWS_DEFAULT_REGION="us-east-2"
